services:
- type: pserv
  name: elasticsearch
  env: docker
  plan: standard
  disk:
    name: esdata
    mountPath: /usr/share/elasticsearch/data
    sizeGB: 10
  autoDeploy: false
  envVars:
  - key: ES_JAVA_OPTS
    value: "-Xms1200m -Xmx1200m"
  - key: discovery.type
    value: single-node
  - key: cluster.name
    value: elastic
  - key: bootstrap.memory_lock
    value: "true"
  # Disable unused X-Pack features
  - key: xpack.ml.enabled
    value: "false"
  - key: xpack.monitoring.enabled
    value: "false"
  - key: xpack.security.enabled
    value: "false"
  - key: xpack.watcher.enabled
    value: "false"
  - key: xpack.logstash.enabled
    value: "false"
  - key: xpack.graph.enabled
    value: "false"
  - key: xpack.deprecation.enabled
    value: "false"
  - key: xpack.geoip.downloader.enabled
    value: "false"
